### PR TITLE
fix: add logging and reporting unhandled errors

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

- Add logging and reporting unhandled errors.

## Motivation and Context

- I thought that `log.catchErrors` records errors automatically but it is not right.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mitosagi** [comment]
I am currently unable to reproduce the condition where log.catchErrors does not log.

**Comment by hal-shu-sato** [comment]
I researched it now.
If you launch the installer, do not push 'OK' in the error dialog, and wait, apm does not log the error.

**Comment by hal-shu-sato** [comment]
Then, it makes me confused because I'm not sure that this PR is necessary.

**Comment by hal-shu-sato** [comment]
I don't think that this PR is necessary.

**Pull request closed without merging**
