### PR TITLE
feat: sort packages on startup

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Set the default package sort order and add a button to filter scripts.

## Related Issue

- #404

## How Has This Been Tested?

- Confirmed filtering operation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mitosagi** [comment]
This is the last PR I want to send before version 3.0.

**Review by hal-shu-sato — APPROVED** [review]
Good improvements.
Did you add `script-dist` in `parsePackageType` for the future?

**Comment by mitosagi** [comment]
I added this because it is needed now to sort by "スクリプト配布サイト" items.

**Comment by hal-shu-sato** [comment]
I see.
Thank you!!

**Pull request merged**
